server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka #default-label: config-server si se trabaja con Git
          uri: https://github.com/Montes-Tobar/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service
  
          
