server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: zipkin-sleuth #Esta es la rama del repositorio que se están utilizando.
          uri: https://github.com/Montes-Tobar/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service
  
          
