server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances #default-label: config-server si se trabaja con Git #Estas son las ramas del repositorio que se están utilizando.
          uri: https://github.com/Montes-Tobar/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service
  
          
